import os
import tempfile
import unittest
from unittest.mock import MagicMock, patch

from zhirterminalassist.agent import AgentSession
from zhirterminalassist.ai import ToolCall

class TestAgent(unittest.TestCase):
    def setUp(self):
        self.tmp_dir = tempfile.TemporaryDirectory()
        self.cwd = self.tmp_dir.name
        self.session = AgentSession(self.cwd)

    def tearDown(self):
        self.tmp_dir.cleanup()

    def test_execute_read_file_tool(self):
        # Create a file
        fpath = os.path.join(self.cwd, "hello.txt")
        with open(fpath, "w") as f:
            f.write("line 1\nline 2\n")

        tc = ToolCall(id="tc_1", name="read_file", arguments={"path": "hello.txt"})
        output = self.session._execute_tool(tc)
        self.assertIn("1 | line 1", output)

    def test_execute_write_file_tool(self):
        tc = ToolCall(id="tc_2", name="write_file", arguments={"path": "new.txt", "content": "test content"})
        # FileManager write_file with confirm_overwrite=False won't ask for new file
        output = self.session._execute_tool(tc)
        self.assertIn("new.txt", output)
        
        # Verify file exists
        self.assertTrue(os.path.exists(os.path.join(self.cwd, "new.txt")))

    def test_execute_list_dir_tool(self):
        tc = ToolCall(id="tc_3", name="list_dir", arguments={"path": "."})
        output = self.session._execute_tool(tc)
        self.assertIsInstance(output, str)

    def test_reset_context(self):
        self.session.messages.append({"role": "user", "content": "hi"})
        self.assertEqual(len(self.session.messages), 1)
        self.session.reset_context()
        self.assertEqual(len(self.session.messages), 0)

    @patch("zhirterminalassist.agent.get_ai_provider")
    def test_run_turn_autonomous_tool_flow(self, mock_provider_getter):
        # Mock AI response: First turn calls tool "write_file", second turn returns final message
        mock_provider = MagicMock()
        mock_provider_getter.return_value = mock_provider

        tool_call = ToolCall(
            id="call_99",
            name="write_file",
            arguments={"path": "auto.txt", "content": "generated by agent"}
        )

        # 1st call: returns a tool call
        # 2nd call: returns final answer
        mock_provider.send_messages.side_effect = [
            ("I will create auto.txt", [tool_call], None),
            ("I have created auto.txt successfully.", [], None)
        ]

        self.session.run_turn("Please create auto.txt")

        # Verify auto.txt exists
        self.assertTrue(os.path.exists(os.path.join(self.cwd, "auto.txt")))
        # Verify messages history has user prompt, assistant tool call, tool result, and final assistant message
        self.assertEqual(len(self.session.messages), 4)

if __name__ == "__main__":
    unittest.main()
